### ISSUE TITLE
singbox转换能否加个pt站点呢？

### ISSUE THREAD

**Issue by baozaodetudou** [DustinWin/clash-geosite#11]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PrivateTracker/PrivateTracker.list 在这里

**Comment by DustinWin** [comment]
在 `private` 里面。

**Comment by baozaodetudou** [comment]
@DustinWin 我看rule-set,privateip,🔒 私有网络 源采用 [GeoLite2/private.txt](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data)、[blackmatrix7/ios_rule_script/Lan](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Lan)（仅 IP）和 [TrackersList](https://github.com/XIU2/TrackersListCollection/blob/master/all.txt)（仅 IP）组合 没有包含私有的tracker

**Comment by DustinWin** [comment]
> rule-set,privateip,🔒 私有网络

`rule-set,private` 包含 [TrackersList](https://github.com/XIU2/TrackersListCollection/blob/master/all.txt) 域名，`rule-set,privateip` 包含 [TrackersList](https://github.com/XIU2/TrackersListCollection/blob/master/all.txt) IP

**Comment by baozaodetudou** [comment]
@DustinWin 是的，但是这个不全，https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PrivateTracker/PrivateTracker.list 这里边好多pt站的私有tracker这里边没有

**Comment by DustinWin** [comment]
> @DustinWin 是的，但是这个不全，https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PrivateTracker/PrivateTracker.list 这里边好多pt站的私有tracker这里边没有

我用的上游是 https://github.com/XIU2/TrackersListCollection ，而这个项目的上游是 https://github.com/ngosang/trackerslist ，XIU2 对 ngosang 的进行了筛选。
