### ISSUE TITLE
fakeip-filter 建议增加api.cloudflare.com

### ISSUE THREAD

**Issue by kingsey** [DustinWin/clash-geosite#12]
ddns使用cloudflare托管时，api.cloudflare.com分流fakeip报错context deadline exceeded，分流至realip后正常。

**Comment by DustinWin** [comment]
我一般是在 [ShellCrash/public/fake_ip_filter.list](https://github.com/juewuy/ShellCrash/blob/dev/public/fake_ip_filter.list) 维护的，你可以直接 Pull。

**Comment by kingsey** [comment]
做了进一步测试，仅当使用lucky的ddns服务并使用本地的shellcrash才有这种报错。换用其他ddns服务或者使用非本地的DNS服务器可以分流至fakeip使用。因此不需要增加到fakeip-filter。

**Comment by dayu2025** [comment]
如果用华硕路由器的ddns，要加*.asuscomm.com
新版的在 ./configs/fake_ip_filter.list

**Comment by DustinWin** [comment]
> 如果用华硕路由器的ddns，要加*.asuscomm.com 新版的在 ./configs/fake_ip_filter.list

具体影响和多场景测试结果呢？
