### ISSUE TITLE
geosite里面没有proxy

### ISSUE THREAD

**Issue by starifly** [DustinWin/clash-geosite#14]
麻烦作者确认一下

**Comment by DustinWin** [comment]
提供更详细的信息。

**Comment by starifly** [comment]
如下配置：
```yaml
rules:
  - GEOSITE,proxy,节点选择
```
导入代理软件后会报错：error: load GeoSite data error, list proxy not found，proxy替换为其它的是可以的，比如youtube

**Comment by DustinWin** [comment]
> 如下配置：
> 
> ```yaml
> rules:
>   - GEOSITE,proxy,节点选择
> ```
> 
> 导入代理软件后会报错：error: load GeoSite data error, list proxy not found，proxy替换为其它的是可以的，比如youtube

哪个代理软件？怎么导入的？有没有手动导入 geosite.dat 文件？能不能详细反馈问题？

**Comment by starifly** [comment]
> > 如下配置：
> > ```yaml
> > rules:
> >   - GEOSITE,proxy,节点选择
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 导入代理软件后会报错：error: load GeoSite data error, list proxy not found，proxy替换为其它的是可以的，比如youtube
> 
> 哪个代理软件？怎么导入的？有没有手动导入 geosite.dat 文件？能不能详细反馈问题？

cmfa，geosite.dat肯定是导入了的，因为用其它的关键字比如youtube、cn等都是正常的

就麻烦确认下是不是打包缺少了proxy，我问另外几个人也是同样的问题

**Comment by DustinWin** [comment]
> > > 如下配置：
> > > ```yaml
> > > rules:
> > >   - GEOSITE,proxy,节点选择
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 导入代理软件后会报错：error: load GeoSite data error, list proxy not found，proxy替换为其它的是可以的，比如youtube
> > 
> > 
> > 哪个代理软件？怎么导入的？有没有手动导入 geosite.dat 文件？能不能详细反馈问题？
> 
> cmfa，geosite.dat肯定是导入了的，因为用其它的关键字比如youtube、cn等都是正常的
> 
> 就麻烦确认下是不是打包缺少了proxy，我问另外几个人也是同样的问题

cmfa 需要进入设置 -> Meta Features -> Geo Files，导入 geodata 规则集文件。不能依赖配置项中的 `geox-url`

**Comment by starifly** [comment]
> > > > 如下配置：
> > > > ```yaml
> > > > rules:
> > > >   - GEOSITE,proxy,节点选择
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 导入代理软件后会报错：error: load GeoSite data error, list proxy not found，proxy替换为其它的是可以的，比如youtube
> > > 
> > > 
> > > 哪个代理软件？怎么导入的？有没有手动导入 geosite.dat 文件？能不能详细反馈问题？
> > 
> > 
> > cmfa，geosite.dat肯定是导入了的，因为用其它的关键字比如youtube、cn等都是正常的
> > 就麻烦确认下是不是打包缺少了proxy，我问另外几个人也是同样的问题
> 
> cmfa 需要进入设置 -> Meta Features -> Geo Files，导入 geodata 规则集文件。不能依赖配置项中的 `geox-url`

明白了，谢谢

**Comment by starifly** [comment]
> > > > 如下配置：
> > > > ```yaml
> > > > rules:
> > > >   - GEOSITE,proxy,节点选择
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 导入代理软件后会报错：error: load GeoSite data error, list proxy not found，proxy替换为其它的是可以的，比如youtube
> > > 
> > > 
> > > 哪个代理软件？怎么导入的？有没有手动导入 geosite.dat 文件？能不能详细反馈问题？
> > 
> > 
> > cmfa，geosite.dat肯定是导入了的，因为用其它的关键字比如youtube、cn等都是正常的
> > 就麻烦确认下是不是打包缺少了proxy，我问另外几个人也是同样的问题
> 
> cmfa 需要进入设置 -> Meta Features -> Geo Files，导入 geodata 规则集文件。不能依赖配置项中的 `geox-url`

明白了感谢🙏🏻
