### ISSUE TITLE
SingBoxV1.9.3 Android unsupported version 2

### ISSUE THREAD

**Issue by ghost** [DustinWin/clash-geosite#16]
When using file [https://github.com/DustinWin/ruleset_geodata/releases/download/sing-box-ruleset/cnip.srs](https://github.com/DustinWin/ruleset_geodata/releases/download/sing-box-ruleset/cnip.srs),

SingBoxV1.9.3 Android's Logs output:

> ERROR router: fetch rule-set cnip: unsupported version: 2

**Comment by DustinWin** [comment]
看 README。

**Comment by choicky** [comment]
sing-box 1.9.3 和 1.9.4 都遇到这个问题。

**Comment by DustinWin** [comment]
> sing-box 1.9.3 和 1.9.4 都遇到这个问题。

必须使用 v1.10.0+ 版本。

**Comment by DustinWin** [comment]
单独给 sing-box v1.9.0 版本的内核生成了[规则集](https://github.com/DustinWin/ruleset_geodata/tree/sing-box-ruleset-compatible)

**Comment by choicky** [comment]
多谢大佬 

> 单独给 sing-box v1.9.0 版本的内核生成了[规则集](https://github.com/DustinWin/ruleset_geodata/tree/sing-box-ruleset-compatible)
