### ISSUE TITLE
求大佬写win-gui-sinbox的教程

### ISSUE THREAD

**Issue by yexinghenglf** [DustinWin/clash-geosite#17]
我尝试了很久都是没打到最后的效果，还请大佬可以出一下教程

**Comment by DustinWin** [comment]
直接裸核跑就可以，教程有写。

**Comment by li12138** [comment]
> 我尝试了很久都是没打到最后的效果，还请大佬可以出一下教程

用软件gui for singbox，比较简单

**Comment by DustinWin** [comment]
> > 我尝试了很久都是没打到最后的效果，还请大佬可以出一下教程
> 
> 用软件gui for singbox，比较简单

裸核就自己导入内核和配置文件就可以了 https://proxy-tutorials.dustinwin.top/posts/share-windows-singboxp-ruleset/
