### ISSUE TITLE
关于 domain_suffix

### ISSUE THREAD

**Issue by widsnoy** [DustinWin/clash-geosite#18]
建议在 domain_suffix 的所有域名前面加上一个 . 以避免错误匹配。

比如 le.com -> .le.com，避免错误匹配 goog~~le.com~~

[参考 issue](https://github.com/SagerNet/sing-box/issues/1189)

**Comment by DustinWin** [comment]
v1.10.0+ 版本的内核已经没有这个问题了。

**Comment by widsnoy** [comment]
> v1.10.0+ 版本的内核已经没有这个问题了。

好吧，我是因为把 ads 规则 block 之后无法打开 google.com（可以正常用 google.jp），猜测是这个原因。看来是其它问题。
