### ISSUE TITLE
GUI.FOR.SINGBOX  如何导入

### ISSUE THREAD

**Issue by Ten-Night** [DustinWin/clash-geosite#19]

**Comment by Ten-Night** [comment]
单一规则集导入  "version": 2,导致 报错

**Comment by ypxun** [comment]
#16

**Comment by DustinWin** [comment]
https://github.com/DustinWin/ruleset_geodata/issues/16#issuecomment-2354472194

**Comment by DustinWin** [comment]
做了兼容 sing-box v1.9.0 版本的 ruleset

**Comment by Ten-Night** [comment]
> 做了兼容 sing-box v1.9.0 版本的 ruleset

请教下GUI.FOR.SINGBOX可以直接使用你配置的那个吗
最后那文件使用那  sing-box 内核

**Comment by DustinWin** [comment]
> > 做了兼容 sing-box v1.9.0 版本的 ruleset
> 
> 请教下GUI.FOR.SINGBOX可以直接使用你配置的那个吗 最后那文件使用那 sing-box 内核

使用哪个版本的内核使用哪个规则集

**Comment by Ten-Night** [comment]
注：

须手动新建“ruleset”文件夹，否则规则集文件不会保存在本地。如导入 [ShellCrash](https://github.com/juewuy/ShellCrash)，可先连接 SSH 后执行命令 mkdir -p $CRASHDIR/ruleset/
以下只是节选，请酌情套用




这一块GUI.FOR.SINGBOX可以使用吗

**Comment by Ten-Night** [comment]
如何快速导入到GUI.FOR.SINGBOX

**Comment by DustinWin** [comment]
> 注：
> 
> 须手动新建“ruleset”文件夹，否则规则集文件不会保存在本地。如导入 [ShellCrash](https://github.com/juewuy/ShellCrash)，可先连接 SSH 后执行命令 mkdir -p $CRASHDIR/ruleset/ 以下只是节选，请酌情套用
> 
> 这一块GUI.FOR.SINGBOX可以使用吗

可以，照葫芦画瓢就行

**Comment by Ten-Night** [comment]
手动添加吗 想要做好之后分享出去好像不方便

**Comment by DustinWin** [comment]
> 手动添加吗 想要做好之后分享出去好像不方便

写在配置文件里啊，`rule_set`
