### ISSUE TITLE
microsoft-cn 0 GeoSite :: Ⓜ️ Microsoft 中国

### ISSUE THREAD

**Issue by gzxiexl** [DustinWin/clash-geosite#2]
microsoft-cn 0 GeoSite 是个空文件 是不是源挂了

**Comment by gzxiexl** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml

不如用这个

**Comment by DustinWin** [comment]
> https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
> 
> 不如用这个

嗯，https://rules.kr328.app 嘎了，你给的这个没有单独筛选出 cn（直连域名），今天给整一下。

**Comment by DustinWin** [comment]
@gzxiexl 问题已修复。
