### ISSUE TITLE
话说你们使用 sing-box 1.9.0 版本的多吗？

### ISSUE THREAD

**Issue by DustinWin** [DustinWin/clash-geosite#20]
本 ruleset 规则集只适配了 sing-box 1.10.0+ 版本，正考虑有没有必要做低版本兼容......

**Comment by DustinWin** [comment]
已经新增了

**Comment by ypxun** [comment]
感觉还是不少的，至少我是喜欢使用正式版，测试版更新太频繁。而且我看10版本的更新改动，官网上也暂时隐藏了，想换10测试版也不知道该改哪些配置项。如果不麻烦的话，希望以后能继续保留正式版的适配。

**Comment by DustinWin** [comment]
> 感觉还是不少的，至少我是喜欢使用正式版，测试版更新太频繁。而且我看10版本的更新改动，官网上也暂时隐藏了，想换10测试版也不知道该改哪些配置项。如果不麻烦的话，希望以后能继续保留正式版的适配。

目前 Release 版仍是 v1.9.0，等 Release v1.10.0 发布后就会删除了。另外 v1.10.0 教程可以看 https://sing-boxp.dustinwin.top/zh/

**Comment by VergilGao** [comment]
建议还是单独做一下分支吧，比如 version 2 的规则，单独开个 tag 保留至少半年也好……

**Comment by DustinWin** [comment]
> 建议还是单独做一下分支吧，比如 version 2 的规则，单独开个 tag 保留至少半年也好……

确实在考虑将 version 1 2 3 都端上来，链接又会有变动。按照 sing-box 的特性，估计还会有 version 4 5 6……暂时考虑保留最新 2 个版本的规则集文件。
