### ISSUE TITLE
ruleset能否添加一个大流量下载的分类

### ISSUE THREAD

**Issue by vstar37** [DustinWin/clash-geosite#21]
首先感谢分享规则，
能否提供一个 ruleset 分流大流量下载，
例如: Google Drive，Google Photo，anaconda源，linux源，homebrew。
如果方便的话，请考虑一下，自己搞不清楚怎么合并，这些站点耗流量好多，因此想单独用低倍率。

**Comment by DustinWin** [comment]
> 首先感谢分享规则， 能否提供一个 ruleset 分流大流量下载， 例如: Google Drive，Google Photo，anaconda源，linux源，homebrew。 如果方便的话，请考虑一下，自己搞不清楚怎么合并，这些站点耗流量好多，因此想单独用低倍率。

这种需求太小众，所以没这个方面的打算。你可以 fork 本项目自己添加数据来源进行生成。
