### ISSUE TITLE
请求添加game_proxy规则集

### ISSUE THREAD

**Issue by zjmsjla** [DustinWin/clash-geosite#26]
如标题，希望可以单独添加一个game_proxy标签，因为能给游戏加速的机场流量比较贵，所以想能给游戏代理单独分配。

**Comment by DustinWin** [comment]
需求太冷门，你可以试试这个 https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Game/Game.yaml

**Comment by zjmsjla** [comment]
好的 非常感谢
