### ISSUE TITLE
ios app store 下载和更新app的流量走了代理

### ISSUE THREAD

**Issue by gzxiexl** [DustinWin/clash-geosite#3]
ios app store 下载和更新app的流量走了代理
查看面板看到
iosapps.itunes.apple.com 走了代理 
实际发现itunes.apple.com 在apple-cn里面 设置了直连
但是apple.com 又在proxy里面 默认走代理了
能否添加*.itunes.apple.com 进apple-cn里

**Comment by gzxiexl** [comment]
geosite:proxy 源采用 [cokebar/gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 生成的 [gfwlist](https://github.com/gfwlist/gfwlist) 和 [blackmatrix7/ios_rule_script/Global](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global)

建议把gfwlist和 [blackmatrix7/ios_rule_script/Global]不要合并，Global走代理问题比较大，我个人遇到的情况是ea和ios app store下载的域名都跑proxy里走了代理，实际上速度还不如直连，而且浪费了机场流量

**Comment by DustinWin** [comment]
> geosite:proxy 源采用 [cokebar/gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 生成的 [gfwlist](https://github.com/gfwlist/gfwlist) 和 [blackmatrix7/ios_rule_script/Global](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global)
> 
> 建议把gfwlist和 [blackmatrix7/ios_rule_script/Global]不要合并，Global走代理问题比较大，我个人遇到的情况是ea和ios app store下载的域名都跑proxy里走了代理，实际上速度还不如直连，而且浪费了机场流量

看来 "Global" 这个源不太靠谱，我再找找另外的好用的源。

**Comment by DustinWin** [comment]
上游 [v2fly/domain-list-community/data/geolocation-!cn](https://github.com/v2fly/domain-list-community/blob/master/data/geolocation-!cn) 就是将 `'+.apple.com'` 走代理的。虽然换了源，但你的问题依然存在，建议自行更改，`apple.com.cn` 才走直连的。

**Comment by gzxiexl** [comment]
是的，我最后还是换成了黑名单模式，白名单模式问题有点多，不适合我这种仅仅是看看油管电报gayhub的人，像apple app store下载直连能跑到百兆以上，走了代理速度一半不到影响体验。

**Comment by DustinWin** [comment]
> 是的，我最后还是换成了黑名单模式，白名单模式问题有点多，不适合我这种仅仅是看看油管电报gayhub的人，像apple app store下载直连能跑到百兆以上，走了代理速度一半不到影响体验。

你的规则配置是按照我的这样设置的？然后查看日志或者“连接”定位到 `apple.com`（完整域名）走了代理导致下载缓慢？

**Comment by appshubcc** [comment]
> > geosite:proxy 源采用 [cokebar/gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 生成的 [gfwlist](https://github.com/gfwlist/gfwlist) 和 [blackmatrix7/ios_rule_script/Global](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global)
> > 建议把gfwlist和 [blackmatrix7/ios_rule_script/Global]不要合并，Global走代理问题比较大，我个人遇到的情况是ea和ios app store下载的域名都跑proxy里走了代理，实际上速度还不如直连，而且浪费了机场流量
> 
> 看来 "Global" 这个源不太靠谱，我再找找另外的好用的源。

这个Global,一言难尽啊,建议换个源,这里有个不错的数据库(需要分类),https://tranco-list.eu/#download

本来想法是通过这个域名做总的分类,先去除去除google等对应的@cn域名,然后再去除tld-not-cn和gfwlist,,然后是ads

这样数据会少很多,个人思路:通过以上精简后,剩下的域名做国内默认DNS解析,返回国外ip(被墙或者污染都是返回国外ip)则判定为proxy,国内则为cn,
这样理论上还是比较精准的,个人因为时间以及能力问题无法实现,老哥有兴趣可以尝试一下,国内服务器若无,我可以提供一个阿里云来用,国内公网DNS都有限制,内网阿里云解析是5000QPS,应该是足够的

**Comment by DustinWin** [comment]
> > > geosite:proxy 源采用 [cokebar/gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 生成的 [gfwlist](https://github.com/gfwlist/gfwlist) 和 [blackmatrix7/ios_rule_script/Global](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global)
> > > 建议把gfwlist和 [blackmatrix7/ios_rule_script/Global]不要合并，Global走代理问题比较大，我个人遇到的情况是ea和ios app store下载的域名都跑proxy里走了代理，实际上速度还不如直连，而且浪费了机场流量
> > 
> > 
> > 看来 "Global" 这个源不太靠谱，我再找找另外的好用的源。
> 
> 这个Global,一言难尽啊,建议换个源,这里有个不错的数据库(需要分类),https://tranco-list.eu/#download
> 
> 本来想法是通过这个域名做总的分类,先去除去除google等对应的[@cn](https://github.com/cn)域名,然后再去除tld-not-cn和gfwlist,,然后是ads
> 
> 这样数据会少很多,个人思路:通过以上精简后,剩下的域名做国内默认DNS解析,返回国外ip(被墙或者污染都是返回国外ip)则判定为proxy,国内则为cn, 这样理论上还是比较精准的,个人因为时间以及能力问题无法实现,老哥有兴趣可以尝试一下,国内服务器若无,我可以提供一个阿里云来用,国内公网DNS都有限制,内网阿里云解析是5000QPS,应该是足够的

已新增 `tld-proxy` 和 `tld-cn`

**Comment by appshubcc** [comment]
> > > > geosite:proxy 源采用 [cokebar/gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 生成的 [gfwlist](https://github.com/gfwlist/gfwlist) 和 [blackmatrix7/ios_rule_script/Global](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global)
> > > > 建议把gfwlist和 [blackmatrix7/ios_rule_script/Global]不要合并，Global走代理问题比较大，我个人遇到的情况是ea和ios app store下载的域名都跑proxy里走了代理，实际上速度还不如直连，而且浪费了机场流量
> > > 
> > > 
> > > 看来 "Global" 这个源不太靠谱，我再找找另外的好用的源。
> > 
> > 
> > 这个Global,一言难尽啊,建议换个源,这里有个不错的数据库(需要分类),https://tranco-list.eu/#download
> > 本来想法是通过这个域名做总的分类,先去除去除google等对应的[@cn](https://github.com/cn)域名,然后再去除tld-not-cn和gfwlist,,然后是ads
> > 这样数据会少很多,个人思路:通过以上精简后,剩下的域名做国内默认DNS解析,返回国外ip(被墙或者污染都是返回国外ip)则判定为proxy,国内则为cn, 这样理论上还是比较精准的,个人因为时间以及能力问题无法实现,老哥有兴趣可以尝试一下,国内服务器若无,我可以提供一个阿里云来用,国内公网DNS都有限制,内网阿里云解析是5000QPS,应该是足够的
> 
> 已新增 `tld-proxy` 和 `tld-cn`

建议tld-proxy 和 tld-cn分别放置于cn和proxy的下面

**Comment by DustinWin** [comment]
> > > > > geosite:proxy 源采用 [cokebar/gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 生成的 [gfwlist](https://github.com/gfwlist/gfwlist) 和 [blackmatrix7/ios_rule_script/Global](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global)
> > > > > 建议把gfwlist和 [blackmatrix7/ios_rule_script/Global]不要合并，Global走代理问题比较大，我个人遇到的情况是ea和ios app store下载的域名都跑proxy里走了代理，实际上速度还不如直连，而且浪费了机场流量
> > > > 
> > > > 
> > > > 看来 "Global" 这个源不太靠谱，我再找找另外的好用的源。
> > > 
> > > 
> > > 这个Global,一言难尽啊,建议换个源,这里有个不错的数据库(需要分类),https://tranco-list.eu/#download
> > > 本来想法是通过这个域名做总的分类,先去除去除google等对应的[@cn](https://github.com/cn)域名,然后再去除tld-not-cn和gfwlist,,然后是ads
> > > 这样数据会少很多,个人思路:通过以上精简后,剩下的域名做国内默认DNS解析,返回国外ip(被墙或者污染都是返回国外ip)则判定为proxy,国内则为cn, 这样理论上还是比较精准的,个人因为时间以及能力问题无法实现,老哥有兴趣可以尝试一下,国内服务器若无,我可以提供一个阿里云来用,国内公网DNS都有限制,内网阿里云解析是5000QPS,应该是足够的
> > 
> > 
> > 已新增 `tld-proxy` 和 `tld-cn`
> 
> 建议tld-proxy 和 tld-cn分别放置于cn和proxy的下面

“上下”根据个人喜好调整吧，我偏好用来提高匹配效率，如白名单模式用 `tld-cn`，黑名单模式用 `tld-proxy`。README.md 文件里的配置也只是做个范例而已。
