### ISSUE TITLE
AI的规则集可以加入claude的吗？谢谢！

### ISSUE THREAD

**Issue by CaptainGod** [DustinWin/clash-geosite#4]
AI的规则集可以加入claude的吗？谢谢！

**Comment by DustinWin** [comment]
> AI的规则集可以加入claude的吗？谢谢！

暂时没有打算，可以 fork 本项目后自行添加。

**Comment by DustinWin** [comment]
> AI的规则集可以加入claude的吗？谢谢！

已添加。
