### ISSUE TITLE
请教下关于default-nameserver的问题

### ISSUE THREAD

**Issue by a39908646** [DustinWin/clash-geosite#5]
为什么要使用default-nameserver呢？
直接用dns的ip会有哪些问题？
nameserver:
    # 策略组内必须有`🪜 代理域名`
    - 'https://1.1.1.1/dns-query#🪜 代理域名&h3=true'
    - 'https://8.8.8.8/dns-query#🪜 代理域名'
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query#h3=true
  nameserver-policy:
    'rule-set:ads': rcode://success
    'rule-set:microsoft-cn,apple-cn,google-cn,games-cn': [https://223.5.5.5/dns-query#h3=true]
    'rule-set:cn,private': [https://223.5.5.5/dns-query#h3=true]

**Comment by DustinWin** [comment]
> 为什么要使用default-nameserver呢？ 直接用dns的ip会有哪些问题？ nameserver: # 策略组内必须有`🪜 代理域名` - '[https://1.1.1.1/dns-query#🪜](https://1.1.1.1/dns-query#%F0%9F%AA%9C) 代理域名&h3=true' - '[https://8.8.8.8/dns-query#🪜](https://8.8.8.8/dns-query#%F0%9F%AA%9C) 代理域名' proxy-server-nameserver: - https://223.5.5.5/dns-query#h3=true nameserver-policy: 'rule-set:ads': rcode://success 'rule-set:microsoft-cn,apple-cn,google-cn,games-cn': [https://223.5.5.5/dns-query#h3=true] 'rule-set:cn,private': [https://223.5.5.5/dns-query#h3=true]

看个人喜好，无所谓的。
