### ISSUE TITLE
CHATGPT IOS 规则

### ISSUE THREAD

**Issue by dudt** [DustinWin/clash-geosite#7]
ios.chat.openai.com
需要添加这一条域名才可以使用,不然会提示VPN警告

**Comment by DustinWin** [comment]
> ios.chat.openai.com 需要添加这一条域名才可以使用,不然会提示VPN警告

里面包含 `DOMAIN-KEYWORD,openai` 规则，可以匹配这条域名。

**Comment by dudt** [comment]
> > ios.chat.openai.com 需要添加这一条域名才可以使用,不然会提示VPN警告
> 
> 里面包含 `DOMAIN-KEYWORD,openai` 规则，可以匹配这条域名。

但是我不添加ios.chat.openai.com 这一条规则会提示 vpn警告导致用不了。
用的https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.list这个

**Comment by DustinWin** [comment]
> > > ios.chat.openai.com 需要添加这一条域名才可以使用,不然会提示VPN警告
> > 
> > 
> > 里面包含 `DOMAIN-KEYWORD,openai` 规则，可以匹配这条域名。
> 
> 但是我不添加ios.chat.openai.com 这一条规则会提示 vpn警告导致用不了。 用的[https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.list这个](https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.list%E8%BF%99%E4%B8%AA)

上游没有这条域名，且 `DOMAIN-KEYWORD,openai` 会匹配 `ios.chat.openai.com`，还有问题就自行添加吧。
[更新]  
抱歉已发现问题（也不算问题），我的规则集中为了增加匹配效率，仅 `applications` 和 `networktest` 这两个规则集包含除**纯域名**外的规则类型，比如 `DOMAIN-KEYWORD`，所以在 `ai` 规则集中并不包含 `DOMAIN-KEYWORD,openai` ，所以无法匹配上 `ios.chat.openai.com`  
解决方法：规则里自行添加 `ios.chat.openai.com` 走代理

**Comment by DustinWin** [comment]
另外反馈问题注明一下使用的是 mihomo 还是 sing-box，是 geodata 还是 ruleset。
