### ISSUE TITLE
.list 的IP列表能否加个no-resolve版本

### ISSUE THREAD

**Issue by lingbaoboy** [DustinWin/clash-geosite#8]
IP列表能否加个no-resolve的版本
我在loon中准备直接中国域名的中国ip（不解析域名）直连，剩下全部代理，如果提前解析会出现DNS泄露

**Comment by DustinWin** [comment]
暂无这方面的计划，该项目专注于 clash 和 sing-box（都支持在配置文件添加 `no-resolve`），有需求可以 fork 后自行修改。
